/* Generated By:JavaCC: Do not edit this line. Java2KotlinConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Java2KotlinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int FLOATING_POINT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int ENCAP = 9;
  /** RegularExpression Id. */
  int STATIC = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int BYTE_T = 16;
  /** RegularExpression Id. */
  int SHORT_T = 17;
  /** RegularExpression Id. */
  int INT_T = 18;
  /** RegularExpression Id. */
  int LONG_T = 19;
  /** RegularExpression Id. */
  int FLOAT_T = 20;
  /** RegularExpression Id. */
  int DOUBLE_T = 21;
  /** RegularExpression Id. */
  int BOOLEAN_T = 22;
  /** RegularExpression Id. */
  int CHAR_T = 23;
  /** RegularExpression Id. */
  int VOID_T = 24;
  /** RegularExpression Id. */
  int STRING_T = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int LPAREN = 30;
  /** RegularExpression Id. */
  int RPAREN = 31;
  /** RegularExpression Id. */
  int COMPARE = 32;
  /** RegularExpression Id. */
  int PLUSPLUS = 33;
  /** RegularExpression Id. */
  int MINUSMINUS = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<INTEGER>",
    "<FLOATING_POINT>",
    "<CHAR>",
    "<STRING>",
    "<ENCAP>",
    "\"static\"",
    "\"for\"",
    "\"do\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "<BYTE_T>",
    "<SHORT_T>",
    "<INT_T>",
    "<LONG_T>",
    "<FLOAT_T>",
    "<DOUBLE_T>",
    "<BOOLEAN_T>",
    "<CHAR_T>",
    "\"void\"",
    "\"String\"",
    "<LETTER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<COMPARE>",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"System.out.println(\"",
    "\"System.console().readLine()\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
  };

}
